name: Selenium Tests

on:
  schedule:
    - cron: '0 * * * *'  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager pandas


      # - name: Run contact us tests
      #   run: pytest test_contactus.py --tb=short --junitxml=results.xml

      # - name: Run privacy policy tests
      #   run: pytest test_privacyPolicy.py --tb=short --junitxml=results.xml

      # - name: Run terms & conditions tests
      #   run: pytest test_termsConditions.py --tb=short --junitxml=results.xml

      # - name: Run FAQs tests
      #   run: pytest test_fAQs.py --tb=short --junitxml=results.xml

      # - name: Run feedback tests
      #   run: pytest test_feedbackPage.py --tb=short --junitxml=results.xml

      # - name: Run 11 Plus link tests
      #   run: pytest test_11Pluslinks.py --tb=short --junitxml=results.xml

      # - name: Run 13 Plus link tests
      #   run: pytest test_13Pluslink.py --tb=short --junitxml=results.xml

      # - name: Run GCSE link tests
      #   run: pytest test_GCSElink.py --tb=short --junitxml=results.xml

      # - name: Run IGCSE link tests
      #   run: pytest test_IGCSElink.py --tb=short --junitxml=results.xml

      # - name: Run AS-Level link tests
      #   run: pytest test_AS-Level.py --tb=short --junitxml=results.xml

      # - name: Run A-Level link tests
      #   run: pytest test_A-Level.py --tb=short --junitxml=results.xml
            
      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png


      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
